import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#001489",
    alignItems: "center",
    justifyContent: "flex-start",
    paddingTop: 60,
  },
  logo: {
    width: 280,
    height: 75,
    marginBottom: 90,
    marginTop: 50,
  },
  innerContainer: {
    width: "85%",
    backgroundColor: "#fff",
    borderRadius: 20,
    alignItems: "center",
    paddingVertical: 32,
    paddingHorizontal: 20,
    elevation: 5,
    marginTop: 30,
  },
  title: {
    fontSize: 36,
    color: "#34405A",
    fontWeight: "600",
    letterSpacing: 2,
    marginBottom: 24,
    paddingHorizontal: 9,
  },
  inputGroup: {
    width: "100%",
    marginBottom: 16,
  },
  label: {
    fontSize: 20,
    color: "#34405A",
    marginBottom: 4,
    marginLeft: 6,
  },
  input: {
    width: "100%",
    height: 40,
    borderWidth: 1,
    borderColor: "#B0B8C1",
    borderRadius: 6,
    paddingHorizontal: 10,
    backgroundColor: "#F8F9FB",
    fontSize: 16,
    color: "#34405A",
  },
  errorMessage: {
    width: "100%",
    color: "#D32F2F",
    fontSize: 14,
    marginTop: -4,
    marginBottom: 8,
    textAlign: "left",
    marginLeft: 4,
  },
  button: {
    marginTop: 30,
    width: "80%",
    height: 48,
    backgroundColor: "#001489",
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
  },
  buttonText: {
    color: "#fff",
    fontSize: 22,
    fontWeight: "500",
    letterSpacing: 1,
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
  },
  helperText: {
    color: "#7A869A",
    fontSize: 12,
    marginTop: 12,
    textAlign: "center",
  },
});

export default styles;
